### ISSUE TITLE
Only notify for a subset of services

### ISSUE THREAD

**Issue by LucasVerneyDGE** [ambanum/CGUs#119]
Hi,

I would be interested in getting notifications only for a subset of services (especially with the upcoming inclusion of the tosback declarations). 

I could handle it on my own, running a separate copy of CGUs, but would it this feature be interesting more broadly? Seems notification code is in https://github.com/ambanum/CGUs/blob/d979a3ac789e071933b8c2940a24b2a4e1bca8de/src/notifier/index.js but I am not very familiar with your SendInBlue setup for notifications.

Depending on your feedback, I can help writing patch / code on this :)

Best,

**Comment by LucasVerneyDGE** [comment]
Thanks for the feedback! I've never used SendInBlue so I'm not 100% sure about the way list management is done there, but I definitely agree that without a GUI this seems quite difficult to handle.

I can think about an RSS-based way, which might be easier? The notifier would output one RSS feed per service (and maybe aggregated RSS feeds by category - say Tourism, Food, Transportation, etc - or global across all services), so that user could track any of the service of their choices easily.

This might be included in the email notification pipeline as well, I know MailChimp offers a way to send notifications based on RSS feeds. Would SendInBlue offer a similar tool?

**Comment by MattiSG** [comment]
RSS is an excellent idea, thanks a lot for suggesting this! 😃

I believe this could be a standard way to expose such functionality with limited cost on our side, by allowing the entire RSS ecosystem to plug into CGUs.

> Would SendInBlue offer a similar tool?

[Yes](https://fr.sendinblue.com/blog/email-rss/)! Which demonstrates even more the relevance of this implementation 😃

We'll still need to create a public domain for this feature to be fully usable, but we can definitely start work on the file format, for example.

Would you feel like suggesting an XML schema for the output?

**Comment by LucasVerneyDGE** [comment]
I'm glad you are happy with the RSS solution. Plus, I've just thought that requiring a SendInBlue to be able to deploy CGUs with notifications could be a quite strong requirement, so I hope having RSS output could help deploy a test CGUs instance more easily.

I can definitely write something for a proof of concept of RSS outputs, which we can further extend afterwards if this is a good match. I'll handle it in the coming days.

**Comment by MattiSG** [comment]
> requiring a SendInBlue to be able to deploy CGUs with notifications could be a quite strong requirement

Totally, which is why we've opted for an events-based architecture and a Notifier class which is fully independent from the rest of the code and could easily be extracted in the future 🙂

**Comment by MattiSG** [comment]
As discussed in https://github.com/ambanum/CGUs/pull/131#issuecomment-696736211, we are now using GitHub-generated Atom feeds for commits. This has been documented in #150 and #154, and fixes this issue since RSS can easily be turned into email generators with third-party tools.

As documented in https://github.com/ambanum/CGUs/pull/131#issuecomment-696831472, we don't have the intention to fully depend on GitHub over time, but it is too early in the life of the product to invest in an independent solution. We first want to assess use cases before generating our own RSS feeds and possibly offer dedicated email notifications.

Thanks again @LucasVerneyDGE for opening this discussion, for contributing a PoC that can act as a basis for future implementations, and for reviewing the documentation! Please let us know of any feedback from users that would use the RSS feature 😃
