### ISSUE TITLE
Validate minimum size after filtering

### ISSUE THREAD

**Issue by MattiSG** [ambanum/CGUs#59]
As discussed this morning with @michielbdejong and @Ndpnt:

Add a validation step  in `scripts/validation/validate.js` to check that the resulting string after filtering a document is at least `n` characters long, where `n` is either arbitrary or computed once as a fraction of the minimum size of all currently tracked documents.

**Comment by michielbdejong** [comment]
I have a question:

We want to add this check both for `npm run validate`, and for the [Tosback2 import script](https://github.com/ambanum/CGUs/pull/71), and obviously we don't want to copy-paste any code in two places. But the existing validation system runs on Mocha.

So I tried to run the Mocha tests from `scripts/validation/validate.js` programmatically in `scripts/tosback-import.js` but it's not that easy to [run Mocha programmatically](https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically), I ran into issues with `require` vs `import` (apparently Mocha uses `require` which is not allowed if you depend on it with `import`, at least that's how far I got). 

Apart from that, making `scripts/tosback-import.js` depend on `scripts/validation/validate.js` sort of makes Mocha into a `dependency` instead of a `devDependency` (my IDE also complains about this), which just feels a bit weird.

So in my work-in-progress branch, I'm already extracting some of the assessment functionality out of tests, for reuse. See for instance https://github.com/ambanum/CGUs/blob/tosback-rules-import/scripts/validation/validate.js#L13.

My question is, should I do the same with these additional checks we're adding? Some checks are quite small (e.g. [fetch timeout](https://github.com/ambanum/CGUs/blob/tosback-rules-import/scripts/validation/validate.js#L50-L53)) and quite integrated with how Mocha runs, but I'm still a bit hesitant to use Mocha programmatically inside the Tosback2 import script.

**Comment by MattiSG** [comment]
> Apart from that, making `scripts/tosback-import.js` depend on `scripts/validation/validate.js` sort of makes Mocha into a `dependency` instead of a `devDependency`

Is it still the case if the import script is considered a dev task? As mentioned in https://github.com/ambanum/CGUs/pull/71#discussion_r466991717 I believe this is the case, so I'm fine with `tosback-import` depending on dev dependencies 🙂

I'm strongly in favor of extracting functionality rather than duplicating code. I wonder, however, how much we should suffer from working around Mocha considering how the validation code looks more like custom code than idiomatic Mocha. Maybe the validation should be a full module exporting validation functions that are then reused by both tosback-import and either a Mocha file or a standalone script that reimplements some of the logging features from Mocha but also stops the madness with skipping tests for document types that are not implemented.

@Ndpnt WDYT?

**Comment by michielbdejong** [comment]
Done:
* https://github.com/ambanum/CGUs/blob/master/scripts/validation/validator.js#L67
* https://github.com/ambanum/CGUs/blob/master/scripts/validation/validate.js#L80
