### ISSUE TITLE
Service-specific document types

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/CGUs#89]
Do we want to crawl a document like https://www.foxnews.com/closed-captioning ?

**Comment by MattiSG** [comment]
It's a tough question.
I see how there would be added value in supporting service-specific policies. However, it could also become a mess quite fast.

I'd say if we have to decide right now it's a no.

In order to better assess the size of the issue and the potential value, do we know how many such service-specific documents are in tosback (in terms of total documents, of proportion of all documents, and of proportion of all service providers)?

**Comment by MattiSG** [comment]
@AdrienFines have you encountered such service-specific document types in the ones you have added manually?

**Comment by AdrienFines** [comment]
> @AdrienFines have you encountered such service-specific document types in the ones you have added manually?
Usually not, except for Twitter (for instance : https://help.twitter.com/en/rules-and-policies/twitter-reach-limited) but I understand that Twitter is quite a special case anyway.

**Comment by MattiSG** [comment]
Thanks to this issue and #88, we have made major changes to the way document types are declared and handled. The WIP can be followed in #90 and input is welcome 🙂

If #90 is merged, I would find it acceptable to accept more niche document types. It will always be possible to later remove the documents that are unique or find some other way to handle them.

**Comment by MattiSG** [comment]
Service-specific document types that should be created are listed in this [mapping table](https://docs.google.com/spreadsheets/d/1RwnWbRdAyBGxOueK1yTv7li_KHmgNbszC4HrY9Lxx68/) from ToSBack types to CGUs types.

These two —hopefully with a slightly widened scope— should be created:

- Closed Captioning Policy
- Seller Warranty
